# permissions for end users to view servicedefaults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicedefault-viewer-role
rules:
- apiGroups:
  - consul.io
  resources:
  - servicedefaults
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - consul.io
  resources:
  - servicedefaults/status
  verbs:
  - get
